# Generated by Django 4.1.9 on 2023-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
        migrations.AlterModelOptions(
            name='trader',
            options={'verbose_name': 'Trader', 'verbose_name_plural': 'Traders'},
        ),
        migrations.AddField(
            model_name='trader',
            name='slug_trader',
            field=models.SlugField(default=0, unique=True, verbose_name='Slug Trader'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trader', 'amount'], name='trading_tra_trader__34da54_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trader', 'profit_loss'], name='trading_tra_trader__789740_idx'),
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['trader', 'slug_trader'], name='trading_tra_trader__8179bf_idx'),
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['name'], name='trading_tra_name_bd9acf_idx'),
        ),
    ]
