# Generated by Django 4.1.9 on 2023-06-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_remove_trader_trading_tra_name_bd9acf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trader',
            name='trading_tra_trader__8179bf_idx',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='slug_trader',
            new_name='slug',
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['trader', 'slug'], name='trading_tra_trader__9cad59_idx'),
        ),
    ]
