# Generated by Django 4.1.9 on 2023-06-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_remove_trader_trading_tra_trader__8179bf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_trader__34da54_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_trader__789740_idx',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='profit_loss',
        ),
        migrations.AddField(
            model_name='trade',
            name='loss',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='Loss'),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='Profit'),
        ),
        migrations.AddField(
            model_name='trader',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='Amount'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trader', 'profit'], name='trading_tra_trader__aaf68e_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trader', 'loss'], name='trading_tra_trader__66c680_idx'),
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['amount'], name='trading_tra_amount_d19f40_idx'),
        ),
    ]
