# Generated by Django 4.1.9 on 2023-06-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_trade_trading_tra_trader__34da54_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_trader__aaf68e_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_trader__66c680_idx',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='profit',
        ),
        migrations.AddField(
            model_name='trade',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='Profit/Loss'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trader', 'balance'], name='trading_tra_trader__f0fe7c_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['trader', 'profit_loss'], name='trading_tra_trader__789740_idx'),
        ),
    ]
